version: '3.7'
services:
  upstream:
    build:
      context: upstream
      dockerfile: Dockerfile
  proxy:
    build:
      context: proxy
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - upstream


